version: '3.8'
services:
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
        container_name: hapster_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - './:/var/www/html'
        networks:
            - hapster_network
        depends_on:
            - mysql
            - redis
    db:
        image: 'mysql:8.0'
        container_name: hapster_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hapster
            MYSQL_USER: hapster
            MYSQL_PASSWORD: secret
        ports:
            - '3306:3306'
        networks:
            - hapster_network
        volumes:
            - 'dbdata:/var/lib/mysql'
    redis:
        image: 'redis:7.0'
        container_name: hapster_redis
        ports:
            - '6379:6379'
        networks:
            - hapster_network
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    hapster_network:
        driver: bridge
volumes:
    dbdata: null
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
